---
- name: Wait for SSH
  wait_for_connection:
    delay: 10
    timeout: 60

- name: Subscribe to RHN
  redhat_subscription:
    state: present
    username:
    password: "{{ registration_password }}"
    pool_ids:

- name: Enable Repos
  rhsm_repository:
    name:
      - rhel-7-server-optional-rpms
      - rhel-7-server-supplementary-rpms

- name: Install Needed Packages
  yum:
    name:
      - bind-utils
      - wget
      - vim
    state: present
