---
- name: Stop/Disable Cloud-Init
  systemd:
    name: cloud-init
    enabled: no
    state: stopped

- name: Setup Network Config
  template:
    src: network.j2
    dest: /etc/sysconfig/network
    owner: root
    group: root
    mode: 0644

- name: Setup Network Interface Config
  template:
    src: ifcfg-eth0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    owner: root
    group: root
    mode: 0644

# Removed below line as I was testing
#- name: Reboot
#  reboot:
